// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDkMT2sCoza7jZDlIvWaJ532pq15JmGQE',
    appId: '1:934910496388:web:4c66e56545339c65c2fcd1',
    messagingSenderId: '934910496388',
    projectId: 'egitim-sorun-project',
    authDomain: 'egitim-sorun-project.firebaseapp.com',
    storageBucket: 'egitim-sorun-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJJo8DWfHKFFv_MOZOkaxblvOsq0TEa3I',
    appId: '1:934910496388:android:d49674c57b18690dc2fcd1',
    messagingSenderId: '934910496388',
    projectId: 'egitim-sorun-project',
    storageBucket: 'egitim-sorun-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChvc8BTspT3mKesqrQ9TNg-_gdIMgitqM',
    appId: '1:934910496388:ios:74960ce4016ca154c2fcd1',
    messagingSenderId: '934910496388',
    projectId: 'egitim-sorun-project',
    storageBucket: 'egitim-sorun-project.appspot.com',
    iosBundleId: 'com.example.bitirmeEgitimSorunlari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChvc8BTspT3mKesqrQ9TNg-_gdIMgitqM',
    appId: '1:934910496388:ios:916904ad236c947ac2fcd1',
    messagingSenderId: '934910496388',
    projectId: 'egitim-sorun-project',
    storageBucket: 'egitim-sorun-project.appspot.com',
    iosBundleId: 'com.example.bitirmeEgitimSorunlari.RunnerTests',
  );
}
